name: project-million
services:
    api:
        image: realestate-api:v1.0
        build:
            context: .
            dockerfile: src/RealEstate.Api/Dockerfile
        container_name: million-api
        ports:
            - "5050:8080"
        # healthcheck:
        #     test: ["CMD-SHELL","curl -f http://million-api:8080/ || exit 1"]
        #     interval: 10s
        #     retries: 3
        #     timeout: 3s
        #     start_period: 10s
        networks:
            network-back:
                priority: 0
networks:
    network-back:
        name: network-back
        driver: bridge
volumes:
    api-data:
        name: api-data